import type { Metadata } from 'next';
import { Great_Vibes, Inter, Fira_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

// Great Vibes は weight が文字列なのでそのまま
const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-greatvibes',
});

// Inter の場合も weight を指定
const geistSans = Inter({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-geist-sans',
});

// Fira Mono の場合も weight を指定
const geistMono = Fira_Mono({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${greatVibes.variable} ${geistSans.variable} ${geistMono.variable} font-sans`}
      >
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}

