import type { Metadata } from 'next';
import { Geist, Geist_Mono, Great_Vibes } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-greatvibes',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${greatVibes.variable} ${geistSans.variable} ${geistMono.variable} font-sans`}
      >
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
